dataBundle\Entity\etat:
    type: entity
    table: null
    repositoryClass: dataBundle\Repository\etatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        vente:
            type: string
            length: 1
        adoption:
            type: string
            length: 1
        accouplement:
            type: string
            length: 1
    oneToMany:
        chien:
            targetEntity: dataBundle\Entity\chien
            mappedBy: etat


    lifecycleCallbacks: {  }
