<?php

namespace userBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * localRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class localRepository extends EntityRepository
{
}
