dog_list:
    path: /
    defaults: { _controller: "dataBundle:dogs:listAll" }
dog_show:
    path:     /{userID}.{dogName}.{dogID}
    defaults: { _controller: "dataBundle:dogs:show" }

dog_edit:
    path:     /{dogID}/modifier
    defaults: { _controller: "dataBundle:dogs:edit" }
dog_update:
    path:     /{dogID}/mise_a_jour
    defaults: { _controller: "dataBundle:dogs:update" }
    methods:  [POST, PUT]

dog_new:
    path:     /nouveau
    defaults: { _controller: "dataBundle:dogs:new" }

dog_create:
    path:     /ajout
    defaults: { _controller: "dataBundle:dogs:create" }
    methods:  POST





test_delete:
    path:     /{id}/delete
    defaults: { _controller: "sampleBundle:test:delete" }
    methods:  [POST, DELETE]
