<?php

namespace dataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * chienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chienRepository extends EntityRepository
{
    public function findForAdoptionDogs()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT C FROM dataBundle:chien C ,dataBundle:etat E WHERE C.etat = E AND E.adoption = 1'
            )
            ->getResult();
    }
    public function findForAccDogs()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT C FROM dataBundle:chien C ,dataBundle:etat E WHERE C.etat = E AND E.accouplement = 1'
            )
            ->getResult();
    }
}
