<?php

namespace dataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * photoDogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class photoDogRepository extends EntityRepository
{
}
